export const state = {
  ui: {
    hoveredColumnIds: [],
    selectedColumnIds: [],
    focusedColumnIds: [],
    visibleColumnIds: [],
    hiddenColumnIds: [],
    draggingColumnIds: [],
    dropTargetColumnIds: [],
    focusedObjectId: "o1",
    loadingOperations: [],
    selectedMatches: [],
  },
  operations: {
    allIds: ["o1"],
    byId: {
      o1: {
        id: "o1",
        name: null,
        databaseName: "o__lqjln8_mklk80b8",
        operationType: "stack",
        parentId: null,
        childIds: ["t1", "t2"],
        columnIds: [],
        hiddenColumnIds: [],
        rowCount: null,
        isMaterialized: false,
        isInSync: false,
        columnCount: null,
      },
    },
    rootOperationId: "o1",
  },
  tables: {
    allIds: ["t1", "t2"],
    byId: {
      t1: {
        id: "t1",
        parentId: "o1",
        source: "file upload",
        databaseName: "t_euonms_mklk7wqw",
        name: "lambert_1",
        fileName: "lambert_1.csv",
        extension: "csv",
        size: 607442,
        mimeType: "text/csv",
        dateLastModified: 1730741525092,
        columnIds: ["c1", "c2"],
        rowCount: 3653,
        hiddenColumnIds: [],
      },
      t2: {
        id: "t2",
        parentId: "o1",
        source: "file upload",
        databaseName: "t_2br19e_mklk7wv4",
        name: "lambert_2",
        fileName: "lambert_2.csv",
        extension: "csv",
        size: 16225,
        mimeType: "text/csv",
        dateLastModified: 1730741525092,
        columnIds: ["c46", "c47"],
        rowCount: 120,
        hiddenColumnIds: [],
      },
    },
  },
  columns: {
    allIds: ["c1", "c2", "c46", "c47"],
    byId: {
      c1: {
        id: "c1",
        parentId: "t1",
        name: null,
        databaseName: "STATION",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: "USW00013994",
        min: "USW00013994",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "USW00013994",
            count: 3653,
          },
        ],
      },
      c2: {
        id: "c2",
        parentId: "t1",
        name: null,
        databaseName: "NAME",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
        min: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
            count: 3653,
          },
        ],
      },
      c46: {
        id: "c46",
        parentId: "t2",
        name: null,
        databaseName: "STATION",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: "USW00013994",
        min: "USW00013994",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "USW00013994",
            count: 120,
          },
        ],
      },
      c47: {
        id: "c47",
        parentId: "t2",
        name: null,
        databaseName: "NAME",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
        min: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
            count: 120,
          },
        ],
      },
    },
  },
  alerts: {
    allIds: [],
    byId: {},
  },
};
