export const state = {
  ui: {
    hoveredColumnIds: [],
    selectedColumnIds: ["c2", "c3", "c4"],
    focusedColumnIds: [],
    visibleColumnIds: [],
    hiddenColumnIds: [],
    draggingColumnIds: [],
    dropTargetColumnIds: [],
    focusedObjectId: "t1",
    selectedTableIds: ["t1"],
    loadingOperations: [],
    selectedMatches: [],
    tableSearchString: "",
  },
  operations: {
    allIds: [],
    byId: {},
    rootOperationId: null,
  },
  tables: {
    allIds: ["t1", "t2", "t3"],
    byId: {
      t1: {
        id: "t1",
        parentId: null,
        source: "file upload",
        databaseName: "t_4oj2pn_mky8sv7m",
        name: "violent_crimes",
        fileName: "violent_crimes.csv",
        extension: "csv",
        size: 4508437,
        mimeType: "text/csv",
        dateLastModified: 1730741525096,
        columnIds: ["c1", "c2", "c3", "c4"],
        rowCount: 64739,
        hiddenColumnIds: [],
      },
      t2: {
        id: "t2",
        parentId: null,
        source: "file upload",
        databaseName: "t_fhojr3_mky8svcb",
        name: "lambert_2",
        fileName: "lambert_2.csv",
        extension: "csv",
        size: 16225,
        mimeType: "text/csv",
        dateLastModified: 1730741525092,
        columnIds: [
          "c5",
          "c6",
          "c7",
          "c8",
          "c9",
          "c10",
          "c11",
          "c12",
          "c13",
          "c14",
          "c15",
          "c16",
          "c17",
          "c18",
          "c19",
          "c20",
          "c21",
          "c22",
          "c23",
          "c24",
          "c25",
        ],
        rowCount: 120,
        hiddenColumnIds: [],
      },
      t3: {
        id: "t3",
        parentId: null,
        source: "file upload",
        databaseName: "t_glzm55_mky8svcp",
        name: "lambert_1",
        fileName: "lambert_1.csv",
        extension: "csv",
        size: 607442,
        mimeType: "text/csv",
        dateLastModified: 1730741525092,
        columnIds: [
          "c26",
          "c27",
          "c28",
          "c29",
          "c30",
          "c31",
          "c32",
          "c33",
          "c34",
          "c35",
          "c36",
          "c37",
          "c38",
          "c39",
          "c40",
          "c41",
          "c42",
          "c43",
          "c44",
          "c45",
          "c46",
          "c47",
          "c48",
          "c49",
          "c50",
          "c51",
          "c52",
          "c53",
          "c54",
          "c55",
          "c56",
          "c57",
          "c58",
          "c59",
          "c60",
          "c61",
          "c62",
          "c63",
          "c64",
          "c65",
          "c66",
          "c67",
          "c68",
          "c69",
          "c70",
        ],
        rowCount: 3653,
        hiddenColumnIds: [],
      },
    },
  },
  columns: {
    allIds: [
      "c1",
      "c2",
      "c3",
      "c4",
      "c5",
      "c6",
      "c7",
      "c8",
      "c9",
      "c10",
      "c11",
      "c12",
      "c13",
      "c14",
      "c15",
      "c16",
      "c17",
      "c18",
      "c19",
      "c20",
      "c21",
      "c22",
      "c23",
      "c24",
      "c25",
      "c26",
      "c27",
      "c28",
      "c29",
      "c30",
      "c31",
      "c32",
      "c33",
      "c34",
      "c35",
      "c36",
      "c37",
      "c38",
      "c39",
      "c40",
      "c41",
      "c42",
      "c43",
      "c44",
      "c45",
      "c46",
      "c47",
      "c48",
      "c49",
      "c50",
      "c51",
      "c52",
      "c53",
      "c54",
      "c55",
      "c56",
      "c57",
      "c58",
      "c59",
      "c60",
      "c61",
      "c62",
      "c63",
      "c64",
      "c65",
      "c66",
      "c67",
      "c68",
      "c69",
      "c70",
    ],
    byId: {
      c1: {
        id: "c1",
        parentId: "t1",
        name: null,
        databaseName: "Date",
        columnType: "VARCHAR",
        approxUnique: 53765,
        avg: null,
        count: 64739,
        max: "2018-04-30T22:26:00",
        min: "1900-01-01T00:00:00",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "2014-12-07T20:30:00",
            count: 40,
          },
          {
            value: "2015-06-20T23:33:00",
            count: 29,
          },
          {
            value: "2012-02-10T16:11:00",
            count: 24,
          },
          {
            value: "2014-08-12T15:00:00",
            count: 20,
          },
          {
            value: "2012-01-01T00:01:00",
            count: 19,
          },
          {
            value: "2017-09-15T22:30:00",
            count: 17,
          },
          {
            value: "2012-04-15T19:47:00",
            count: 17,
          },
          {
            value: "2010-04-08T15:25:00",
            count: 17,
          },
          {
            value: "2010-01-01T00:01:00",
            count: 16,
          },
          {
            value: "2010-01-22T18:53:00",
            count: 15,
          },
          {
            value: "2017-09-15T09:00:00",
            count: 15,
          },
          {
            value: "2012-03-17T20:32:00",
            count: 15,
          },
          {
            value: "2008-11-29T21:07:00",
            count: 14,
          },
          {
            value: "2009-02-05T20:05:00",
            count: 14,
          },
          {
            value: "2009-03-20T21:40:00",
            count: 14,
          },
          {
            value: "2014-01-01T00:01:00",
            count: 13,
          },
          {
            value: "2010-08-28T21:10:00",
            count: 12,
          },
          {
            value: "2011-05-07T01:14:00",
            count: 12,
          },
          {
            value: "2014-11-24T22:00:00",
            count: 11,
          },
          {
            value: "2018-01-24T18:00:00",
            count: 11,
          },
        ],
      },
      c2: {
        id: "c2",
        parentId: "t1",
        name: null,
        databaseName: "Count",
        columnType: "DOUBLE",
        approxUnique: 2,
        avg: 0.9653068474953274,
        count: 64739,
        max: 1,
        min: -1,
        nullPercentage: 0,
        std: 0.2611201703973508,
        topValues: [
          {
            value: "1.0",
            count: 63616,
          },
          {
            value: "-1.0",
            count: 1123,
          },
        ],
      },
      c3: {
        id: "c3",
        parentId: "t1",
        name: null,
        databaseName: "Crime",
        columnType: "DOUBLE",
        approxUnique: 160,
        avg: 36789.82055638796,
        count: 64739,
        max: 44205,
        min: 10000,
        nullPercentage: 0,
        std: 7437.627729958122,
        topValues: [
          {
            value: "41011.0",
            count: 12573,
          },
          {
            value: "31111.0",
            count: 9612,
          },
          {
            value: "31421.0",
            count: 4551,
          },
          {
            value: "41013.0",
            count: 3810,
          },
          {
            value: "43012.0",
            count: 2589,
          },
          {
            value: "21000.0",
            count: 2581,
          },
          {
            value: "43013.0",
            count: 2368,
          },
          {
            value: "41021.0",
            count: 2185,
          },
          {
            value: "10000.0",
            count: 1778,
          },
          {
            value: "42011.0",
            count: 1309,
          },
          {
            value: "43015.0",
            count: 1277,
          },
          {
            value: "43016.0",
            count: 1247,
          },
          {
            value: "31112.0",
            count: 1125,
          },
          {
            value: "41016.0",
            count: 1001,
          },
          {
            value: "42013.0",
            count: 857,
          },
          {
            value: "32111.0",
            count: 810,
          },
          {
            value: "42014.0",
            count: 796,
          },
          {
            value: "36111.0",
            count: 786,
          },
          {
            value: "44015.0",
            count: 750,
          },
          {
            value: "44013.0",
            count: 662,
          },
        ],
      },
      c4: {
        id: "c4",
        parentId: "t1",
        name: null,
        databaseName: "Description",
        columnType: "VARCHAR",
        approxUnique: 210,
        avg: null,
        count: 64739,
        max: "ROBBERY-RESIDENCE/STRNGARM/NO INJ/SUCCESS",
        min: "AGG.ASSAULT-FIREARM/CITIZEN ADULT 1ST DEGREE",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "AGG.ASSAULT-FIREARM/CITIZEN ADULT 1ST DEGREE",
            count: 12394,
          },
          {
            value: "ROBBERY-HIGHWAY  /FIREARM USED/SUCCESSFUL",
            count: 9533,
          },
          {
            value: "ROBBERY-HIGHWAY  /STRNGARM/NO INJ/SUCCESS",
            count: 4524,
          },
          {
            value: "AGG.ASSAULT-FIREARM/CITIZEN ADULT 3RD DEGREE",
            count: 3774,
          },
          {
            value: "AGG.ASSAULT-OTH DANG WEP/CTZEN ADLT 2ND DEGREE",
            count: 2573,
          },
          {
            value: "RAPE -- FORCIBLE",
            count: 2559,
          },
          {
            value: "AGG.ASSAULT-OTH DANG WEP/CTZEN ADLT 3RD DEGREE",
            count: 2332,
          },
          {
            value: "AGG.ASSAULT-FIREARM/CITIZEN CHILD 1ST DEGREE",
            count: 2164,
          },
          {
            value: "HOMICIDE",
            count: 1762,
          },
          {
            value: "AGG.ASSAULT-KNIFE/CITIZEN ADULT 1ST DEGREE",
            count: 1301,
          },
          {
            value: "ASSLT-AGGRAV-OTH-WPN-2ND-ADULT-DOMESTIC",
            count: 1274,
          },
          {
            value: "ASSLT-AGGRAV-OTH-WPN-3RD-ADULT-DOMESTIC",
            count: 1230,
          },
          {
            value: "ROBBERY-HIGHWAY     /FIREARM USED/ATTEMPT",
            count: 1117,
          },
          {
            value: "ASSLT-AGGRAV-FIREARM-3RD-ADULT-DOMESTIC",
            count: 982,
          },
          {
            value: "AGG.ASSAULT-KNIFE/CITIZEN ADULT 3RD DEGREE",
            count: 851,
          },
          {
            value: "ROBBERY-RESIDENCE/FIREARM USED/SUCCESSFUL",
            count: 805,
          },
          {
            value: "ASSLT-AGGRV-KNIFE/CUT-1ST-ADULT-DOMESTIC",
            count: 791,
          },
          {
            value: "ROBBERY-COMMERCE PL/FIREARM USED/SUCCESS",
            count: 773,
          },
          {
            value: "ASSLT-AGGRV-HND/FST/FT-2ND-ADUL-DOMESTIC",
            count: 743,
          },
          {
            value: "AGG.ASSAULT-HNDS,FST,FEET/CTZEN ADLT 3RD DEGRE",
            count: 651,
          },
        ],
      },
      c5: {
        id: "c5",
        parentId: "t2",
        name: null,
        databaseName: "STATION",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: "USW00013994",
        min: "USW00013994",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "USW00013994",
            count: 120,
          },
        ],
      },
      c6: {
        id: "c6",
        parentId: "t2",
        name: null,
        databaseName: "NAME",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
        min: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
            count: 120,
          },
        ],
      },
      c7: {
        id: "c7",
        parentId: "t2",
        name: null,
        databaseName: "DATE",
        columnType: "VARCHAR",
        approxUnique: 123,
        avg: null,
        count: 120,
        max: "2018-04-30",
        min: "2018-01-01",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "2018-01-03",
            count: 1,
          },
          {
            value: "2018-01-05",
            count: 1,
          },
          {
            value: "2018-01-06",
            count: 1,
          },
          {
            value: "2018-01-07",
            count: 1,
          },
          {
            value: "2018-01-09",
            count: 1,
          },
          {
            value: "2018-01-10",
            count: 1,
          },
          {
            value: "2018-01-11",
            count: 1,
          },
          {
            value: "2018-01-12",
            count: 1,
          },
          {
            value: "2018-01-13",
            count: 1,
          },
          {
            value: "2018-01-14",
            count: 1,
          },
          {
            value: "2018-01-15",
            count: 1,
          },
          {
            value: "2018-01-17",
            count: 1,
          },
          {
            value: "2018-01-18",
            count: 1,
          },
          {
            value: "2018-01-19",
            count: 1,
          },
          {
            value: "2018-01-20",
            count: 1,
          },
          {
            value: "2018-01-16",
            count: 1,
          },
          {
            value: "2018-01-08",
            count: 1,
          },
          {
            value: "2018-01-04",
            count: 1,
          },
          {
            value: "2018-01-02",
            count: 1,
          },
          {
            value: "2018-01-01",
            count: 1,
          },
        ],
      },
      c8: {
        id: "c8",
        parentId: "t2",
        name: null,
        databaseName: "PRCP",
        columnType: "DOUBLE",
        approxUnique: 28,
        avg: 0.1323333333333333,
        count: 120,
        max: 1.73,
        min: 0,
        nullPercentage: 0,
        std: 0.31127747985966975,
        topValues: [
          {
            value: "0.0",
            count: 80,
          },
          {
            value: "0.01",
            count: 5,
          },
          {
            value: "0.26",
            count: 3,
          },
          {
            value: "0.02",
            count: 2,
          },
          {
            value: "0.04",
            count: 2,
          },
          {
            value: "0.28",
            count: 2,
          },
          {
            value: "0.27",
            count: 2,
          },
          {
            value: "0.03",
            count: 1,
          },
          {
            value: "1.04",
            count: 1,
          },
          {
            value: "0.76",
            count: 1,
          },
          {
            value: "0.29",
            count: 1,
          },
          {
            value: "0.31",
            count: 1,
          },
          {
            value: "1.73",
            count: 1,
          },
          {
            value: "0.89",
            count: 1,
          },
          {
            value: "1.43",
            count: 1,
          },
          {
            value: "0.1",
            count: 1,
          },
          {
            value: "0.34",
            count: 1,
          },
          {
            value: "0.62",
            count: 1,
          },
          {
            value: "0.2",
            count: 1,
          },
          {
            value: "0.13",
            count: 1,
          },
        ],
      },
      c9: {
        id: "c9",
        parentId: "t2",
        name: null,
        databaseName: "PRCP_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 2,
        avg: null,
        count: 120,
        max: "T,,W,2400",
        min: ",,W,2400",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: ",,W,2400",
            count: 84,
          },
          {
            value: "T,,W,2400",
            count: 36,
          },
        ],
      },
      c10: {
        id: "c10",
        parentId: "t2",
        name: null,
        databaseName: "TMAX",
        columnType: "DOUBLE",
        approxUnique: 59,
        avg: 49.8,
        count: 120,
        max: 85,
        min: 9,
        nullPercentage: 0,
        std: 15.543703634883022,
        topValues: [
          {
            value: "48.0",
            count: 7,
          },
          {
            value: "57.0",
            count: 6,
          },
          {
            value: "50.0",
            count: 5,
          },
          {
            value: "69.0",
            count: 5,
          },
          {
            value: "43.0",
            count: 5,
          },
          {
            value: "53.0",
            count: 4,
          },
          {
            value: "56.0",
            count: 4,
          },
          {
            value: "60.0",
            count: 4,
          },
          {
            value: "62.0",
            count: 4,
          },
          {
            value: "38.0",
            count: 4,
          },
          {
            value: "42.0",
            count: 4,
          },
          {
            value: "34.0",
            count: 3,
          },
          {
            value: "72.0",
            count: 3,
          },
          {
            value: "59.0",
            count: 3,
          },
          {
            value: "66.0",
            count: 3,
          },
          {
            value: "52.0",
            count: 3,
          },
          {
            value: "51.0",
            count: 3,
          },
          {
            value: "45.0",
            count: 3,
          },
          {
            value: "39.0",
            count: 2,
          },
          {
            value: "29.0",
            count: 2,
          },
        ],
      },
      c11: {
        id: "c11",
        parentId: "t2",
        name: null,
        databaseName: "TMAX_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 120,
          },
        ],
      },
      c12: {
        id: "c12",
        parentId: "t2",
        name: null,
        databaseName: "TMIN",
        columnType: "DOUBLE",
        approxUnique: 46,
        avg: 30.408333333333335,
        count: 120,
        max: 61,
        min: -6,
        nullPercentage: 0,
        std: 12.963747664213482,
        topValues: [
          {
            value: "30.0",
            count: 7,
          },
          {
            value: "34.0",
            count: 7,
          },
          {
            value: "40.0",
            count: 6,
          },
          {
            value: "28.0",
            count: 6,
          },
          {
            value: "31.0",
            count: 5,
          },
          {
            value: "39.0",
            count: 5,
          },
          {
            value: "27.0",
            count: 5,
          },
          {
            value: "32.0",
            count: 5,
          },
          {
            value: "36.0",
            count: 4,
          },
          {
            value: "19.0",
            count: 4,
          },
          {
            value: "33.0",
            count: 4,
          },
          {
            value: "25.0",
            count: 3,
          },
          {
            value: "35.0",
            count: 3,
          },
          {
            value: "16.0",
            count: 3,
          },
          {
            value: "44.0",
            count: 3,
          },
          {
            value: "51.0",
            count: 3,
          },
          {
            value: "50.0",
            count: 3,
          },
          {
            value: "42.0",
            count: 3,
          },
          {
            value: "38.0",
            count: 3,
          },
          {
            value: "8.0",
            count: 2,
          },
        ],
      },
      c13: {
        id: "c13",
        parentId: "t2",
        name: null,
        databaseName: "TMIN_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 120,
          },
        ],
      },
      c14: {
        id: "c14",
        parentId: "t2",
        name: null,
        databaseName: "WT01",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.7,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 36,
          },
        ],
      },
      c15: {
        id: "c15",
        parentId: "t2",
        name: null,
        databaseName: "WT01_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.7,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 36,
          },
        ],
      },
      c16: {
        id: "c16",
        parentId: "t2",
        name: null,
        databaseName: "WT02",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.975,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 3,
          },
        ],
      },
      c17: {
        id: "c17",
        parentId: "t2",
        name: null,
        databaseName: "WT02_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.975,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 3,
          },
        ],
      },
      c18: {
        id: "c18",
        parentId: "t2",
        name: null,
        databaseName: "WT03",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.9,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 12,
          },
        ],
      },
      c19: {
        id: "c19",
        parentId: "t2",
        name: null,
        databaseName: "WT03_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.9,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 12,
          },
        ],
      },
      c20: {
        id: "c20",
        parentId: "t2",
        name: null,
        databaseName: "WT04",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.9833,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 2,
          },
        ],
      },
      c21: {
        id: "c21",
        parentId: "t2",
        name: null,
        databaseName: "WT04_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.9833,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 2,
          },
        ],
      },
      c22: {
        id: "c22",
        parentId: "t2",
        name: null,
        databaseName: "WT06",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.9917,
        std: null,
        topValues: [
          {
            value: "1.0",
            count: 1,
          },
        ],
      },
      c23: {
        id: "c23",
        parentId: "t2",
        name: null,
        databaseName: "WT06_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.9917,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 1,
          },
        ],
      },
      c24: {
        id: "c24",
        parentId: "t2",
        name: null,
        databaseName: "WT08",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.9583,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 5,
          },
        ],
      },
      c25: {
        id: "c25",
        parentId: "t2",
        name: null,
        databaseName: "WT08_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.9583,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 5,
          },
        ],
      },
      c26: {
        id: "c26",
        parentId: "t3",
        name: null,
        databaseName: "STATION",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: "USW00013994",
        min: "USW00013994",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "USW00013994",
            count: 3653,
          },
        ],
      },
      c27: {
        id: "c27",
        parentId: "t3",
        name: null,
        databaseName: "NAME",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
        min: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
            count: 3653,
          },
        ],
      },
      c28: {
        id: "c28",
        parentId: "t3",
        name: null,
        databaseName: "DATE",
        columnType: "VARCHAR",
        approxUnique: 2650,
        avg: null,
        count: 3653,
        max: "2017-12-31",
        min: "2008-01-01",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "2008-01-03",
            count: 1,
          },
          {
            value: "2008-01-05",
            count: 1,
          },
          {
            value: "2008-01-06",
            count: 1,
          },
          {
            value: "2008-01-07",
            count: 1,
          },
          {
            value: "2008-01-09",
            count: 1,
          },
          {
            value: "2008-01-10",
            count: 1,
          },
          {
            value: "2008-01-11",
            count: 1,
          },
          {
            value: "2008-01-12",
            count: 1,
          },
          {
            value: "2008-01-13",
            count: 1,
          },
          {
            value: "2008-01-14",
            count: 1,
          },
          {
            value: "2008-01-15",
            count: 1,
          },
          {
            value: "2008-01-17",
            count: 1,
          },
          {
            value: "2008-01-18",
            count: 1,
          },
          {
            value: "2008-01-19",
            count: 1,
          },
          {
            value: "2008-01-20",
            count: 1,
          },
          {
            value: "2008-01-16",
            count: 1,
          },
          {
            value: "2008-01-08",
            count: 1,
          },
          {
            value: "2008-01-04",
            count: 1,
          },
          {
            value: "2008-01-02",
            count: 1,
          },
          {
            value: "2008-01-01",
            count: 1,
          },
        ],
      },
      c29: {
        id: "c29",
        parentId: "t3",
        name: null,
        databaseName: "PRCP",
        columnType: "DOUBLE",
        approxUnique: 196,
        avg: 0.12396934026827236,
        count: 3653,
        max: 4.87,
        min: 0,
        nullPercentage: 0,
        std: 0.3537615287351975,
        topValues: [
          {
            value: "0.0",
            count: 2487,
          },
          {
            value: "0.01",
            count: 122,
          },
          {
            value: "0.02",
            count: 66,
          },
          {
            value: "0.03",
            count: 50,
          },
          {
            value: "0.04",
            count: 48,
          },
          {
            value: "0.05",
            count: 33,
          },
          {
            value: "0.08",
            count: 30,
          },
          {
            value: "0.06",
            count: 30,
          },
          {
            value: "0.07",
            count: 29,
          },
          {
            value: "0.14",
            count: 26,
          },
          {
            value: "0.09",
            count: 26,
          },
          {
            value: "0.1",
            count: 25,
          },
          {
            value: "0.13",
            count: 18,
          },
          {
            value: "0.12",
            count: 17,
          },
          {
            value: "0.15",
            count: 16,
          },
          {
            value: "0.16",
            count: 15,
          },
          {
            value: "0.11",
            count: 15,
          },
          {
            value: "0.19",
            count: 15,
          },
          {
            value: "0.25",
            count: 15,
          },
          {
            value: "0.21",
            count: 14,
          },
        ],
      },
      c30: {
        id: "c30",
        parentId: "t3",
        name: null,
        databaseName: "PRCP_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 9,
        avg: null,
        count: 3653,
        max: "T,,Z,2400",
        min: ",,0,2400",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: ",,W,2400",
            count: 1486,
          },
          {
            value: ",,0,2400",
            count: 929,
          },
          {
            value: ",,X,2400",
            count: 700,
          },
          {
            value: "T,,W,2400",
            count: 250,
          },
          {
            value: "T,,0,2400",
            count: 167,
          },
          {
            value: "T,,X,2400",
            count: 117,
          },
          {
            value: ",,Z,2400",
            count: 3,
          },
          {
            value: "T,,Z,2400",
            count: 1,
          },
        ],
      },
      c31: {
        id: "c31",
        parentId: "t3",
        name: null,
        databaseName: "TMAX",
        columnType: "DOUBLE",
        approxUnique: 129,
        avg: 67.61127840131398,
        count: 3653,
        max: 108,
        min: 2,
        nullPercentage: 0,
        std: 20.295233412524645,
        topValues: [
          {
            value: "83.0",
            count: 108,
          },
          {
            value: "88.0",
            count: 93,
          },
          {
            value: "87.0",
            count: 87,
          },
          {
            value: "84.0",
            count: 83,
          },
          {
            value: "82.0",
            count: 81,
          },
          {
            value: "81.0",
            count: 78,
          },
          {
            value: "85.0",
            count: 77,
          },
          {
            value: "92.0",
            count: 70,
          },
          {
            value: "93.0",
            count: 69,
          },
          {
            value: "80.0",
            count: 69,
          },
          {
            value: "79.0",
            count: 69,
          },
          {
            value: "77.0",
            count: 68,
          },
          {
            value: "90.0",
            count: 67,
          },
          {
            value: "86.0",
            count: 66,
          },
          {
            value: "91.0",
            count: 66,
          },
          {
            value: "75.0",
            count: 65,
          },
          {
            value: "76.0",
            count: 63,
          },
          {
            value: "89.0",
            count: 62,
          },
          {
            value: "71.0",
            count: 62,
          },
          {
            value: "66.0",
            count: 60,
          },
        ],
      },
      c32: {
        id: "c32",
        parentId: "t3",
        name: null,
        databaseName: "TMAX_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 4,
        avg: null,
        count: 3653,
        max: ",,Z",
        min: ",,0",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 1743,
          },
          {
            value: ",,0",
            count: 1089,
          },
          {
            value: ",,X",
            count: 819,
          },
          {
            value: ",,Z",
            count: 2,
          },
        ],
      },
      c33: {
        id: "c33",
        parentId: "t3",
        name: null,
        databaseName: "TMIN",
        columnType: "DOUBLE",
        approxUnique: 112,
        avg: 48.863947440459896,
        count: 3653,
        max: 86,
        min: -8,
        nullPercentage: 0,
        std: 19.0415279568793,
        topValues: [
          {
            value: "67.0",
            count: 85,
          },
          {
            value: "70.0",
            count: 81,
          },
          {
            value: "72.0",
            count: 78,
          },
          {
            value: "65.0",
            count: 75,
          },
          {
            value: "69.0",
            count: 75,
          },
          {
            value: "71.0",
            count: 74,
          },
          {
            value: "73.0",
            count: 74,
          },
          {
            value: "34.0",
            count: 71,
          },
          {
            value: "59.0",
            count: 71,
          },
          {
            value: "66.0",
            count: 70,
          },
          {
            value: "52.0",
            count: 69,
          },
          {
            value: "63.0",
            count: 68,
          },
          {
            value: "60.0",
            count: 68,
          },
          {
            value: "62.0",
            count: 67,
          },
          {
            value: "42.0",
            count: 64,
          },
          {
            value: "50.0",
            count: 64,
          },
          {
            value: "64.0",
            count: 64,
          },
          {
            value: "75.0",
            count: 64,
          },
          {
            value: "41.0",
            count: 63,
          },
          {
            value: "54.0",
            count: 63,
          },
        ],
      },
      c34: {
        id: "c34",
        parentId: "t3",
        name: null,
        databaseName: "TMIN_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 4,
        avg: null,
        count: 3653,
        max: ",,Z",
        min: ",,0",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 1743,
          },
          {
            value: ",,0",
            count: 1089,
          },
          {
            value: ",,X",
            count: 820,
          },
          {
            value: ",,Z",
            count: 1,
          },
        ],
      },
      c35: {
        id: "c35",
        parentId: "t3",
        name: null,
        databaseName: "WT01",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.7186,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 1028,
          },
        ],
      },
      c36: {
        id: "c36",
        parentId: "t3",
        name: null,
        databaseName: "WT01_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 3,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,0",
        nullPercentage: 0.7186,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 825,
          },
          {
            value: ",,0",
            count: 155,
          },
          {
            value: ",,X",
            count: 48,
          },
        ],
      },
      c37: {
        id: "c37",
        parentId: "t3",
        name: null,
        databaseName: "WT02",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9767,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 85,
          },
        ],
      },
      c38: {
        id: "c38",
        parentId: "t3",
        name: null,
        databaseName: "WT02_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 2,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,W",
        nullPercentage: 0.9767,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 51,
          },
          {
            value: ",,W",
            count: 34,
          },
        ],
      },
      c39: {
        id: "c39",
        parentId: "t3",
        name: null,
        databaseName: "WT03",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.8637,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 498,
          },
        ],
      },
      c40: {
        id: "c40",
        parentId: "t3",
        name: null,
        databaseName: "WT03_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 3,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,0",
        nullPercentage: 0.8637,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 281,
          },
          {
            value: ",,W",
            count: 209,
          },
          {
            value: ",,0",
            count: 8,
          },
        ],
      },
      c41: {
        id: "c41",
        parentId: "t3",
        name: null,
        databaseName: "WT04",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9833,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 61,
          },
        ],
      },
      c42: {
        id: "c42",
        parentId: "t3",
        name: null,
        databaseName: "WT04_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 3,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,0",
        nullPercentage: 0.9833,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 43,
          },
          {
            value: ",,W",
            count: 12,
          },
          {
            value: ",,0",
            count: 6,
          },
        ],
      },
      c43: {
        id: "c43",
        parentId: "t3",
        name: null,
        databaseName: "WT05",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.8993,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 368,
          },
        ],
      },
      c44: {
        id: "c44",
        parentId: "t3",
        name: null,
        databaseName: "WT05_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 3,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,0",
        nullPercentage: 0.8993,
        std: null,
        topValues: [
          {
            value: ",,0",
            count: 350,
          },
          {
            value: ",,W",
            count: 11,
          },
          {
            value: ",,X",
            count: 7,
          },
        ],
      },
      c45: {
        id: "c45",
        parentId: "t3",
        name: null,
        databaseName: "WT06",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9926,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 27,
          },
        ],
      },
      c46: {
        id: "c46",
        parentId: "t3",
        name: null,
        databaseName: "WT06_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 2,
        avg: null,
        count: 3653,
        max: ",,W",
        min: ",,0",
        nullPercentage: 0.9926,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 22,
          },
          {
            value: ",,0",
            count: 5,
          },
        ],
      },
      c47: {
        id: "c47",
        parentId: "t3",
        name: null,
        databaseName: "WT07",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9636,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 133,
          },
        ],
      },
      c48: {
        id: "c48",
        parentId: "t3",
        name: null,
        databaseName: "WT07_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 2,
        avg: null,
        count: 3653,
        max: ",,W",
        min: ",,0",
        nullPercentage: 0.9636,
        std: null,
        topValues: [
          {
            value: ",,0",
            count: 132,
          },
          {
            value: ",,W",
            count: 1,
          },
        ],
      },
      c49: {
        id: "c49",
        parentId: "t3",
        name: null,
        databaseName: "WT08",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.8352,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 602,
          },
        ],
      },
      c50: {
        id: "c50",
        parentId: "t3",
        name: null,
        databaseName: "WT08_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 3,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,0",
        nullPercentage: 0.8352,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 366,
          },
          {
            value: ",,X",
            count: 224,
          },
          {
            value: ",,0",
            count: 12,
          },
        ],
      },
      c51: {
        id: "c51",
        parentId: "t3",
        name: null,
        databaseName: "WT09",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9934,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 24,
          },
        ],
      },
      c52: {
        id: "c52",
        parentId: "t3",
        name: null,
        databaseName: "WT09_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 2,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,0",
        nullPercentage: 0.9934,
        std: null,
        topValues: [
          {
            value: ",,0",
            count: 18,
          },
          {
            value: ",,X",
            count: 6,
          },
        ],
      },
      c53: {
        id: "c53",
        parentId: "t3",
        name: null,
        databaseName: "WT10",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9997,
        std: null,
        topValues: [
          {
            value: "1.0",
            count: 1,
          },
        ],
      },
      c54: {
        id: "c54",
        parentId: "t3",
        name: null,
        databaseName: "WT10_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.9997,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 1,
          },
        ],
      },
      c55: {
        id: "c55",
        parentId: "t3",
        name: null,
        databaseName: "WT11",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9948,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 19,
          },
        ],
      },
      c56: {
        id: "c56",
        parentId: "t3",
        name: null,
        databaseName: "WT11_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,X",
        nullPercentage: 0.9948,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 19,
          },
        ],
      },
      c57: {
        id: "c57",
        parentId: "t3",
        name: null,
        databaseName: "WT13",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.8615,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 506,
          },
        ],
      },
      c58: {
        id: "c58",
        parentId: "t3",
        name: null,
        databaseName: "WT13_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,X",
        nullPercentage: 0.8615,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 506,
          },
        ],
      },
      c59: {
        id: "c59",
        parentId: "t3",
        name: null,
        databaseName: "WT14",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9494,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 185,
          },
        ],
      },
      c60: {
        id: "c60",
        parentId: "t3",
        name: null,
        databaseName: "WT14_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,X",
        nullPercentage: 0.9494,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 185,
          },
        ],
      },
      c61: {
        id: "c61",
        parentId: "t3",
        name: null,
        databaseName: "WT15",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9975,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 9,
          },
        ],
      },
      c62: {
        id: "c62",
        parentId: "t3",
        name: null,
        databaseName: "WT15_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,X",
        nullPercentage: 0.9975,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 9,
          },
        ],
      },
      c63: {
        id: "c63",
        parentId: "t3",
        name: null,
        databaseName: "WT16",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.7846,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 787,
          },
        ],
      },
      c64: {
        id: "c64",
        parentId: "t3",
        name: null,
        databaseName: "WT16_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 2,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,0",
        nullPercentage: 0.7846,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 671,
          },
          {
            value: ",,0",
            count: 116,
          },
        ],
      },
      c65: {
        id: "c65",
        parentId: "t3",
        name: null,
        databaseName: "WT17",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9967,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 12,
          },
        ],
      },
      c66: {
        id: "c66",
        parentId: "t3",
        name: null,
        databaseName: "WT17_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,X",
        nullPercentage: 0.9967,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 12,
          },
        ],
      },
      c67: {
        id: "c67",
        parentId: "t3",
        name: null,
        databaseName: "WT18",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.9431,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 208,
          },
        ],
      },
      c68: {
        id: "c68",
        parentId: "t3",
        name: null,
        databaseName: "WT18_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 2,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,0",
        nullPercentage: 0.9431,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 178,
          },
          {
            value: ",,0",
            count: 30,
          },
        ],
      },
      c69: {
        id: "c69",
        parentId: "t3",
        name: null,
        databaseName: "WT22",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 3653,
        max: 1,
        min: 1,
        nullPercentage: 0.997,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 11,
          },
        ],
      },
      c70: {
        id: "c70",
        parentId: "t3",
        name: null,
        databaseName: "WT22_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 3653,
        max: ",,X",
        min: ",,X",
        nullPercentage: 0.997,
        std: null,
        topValues: [
          {
            value: ",,X",
            count: 11,
          },
        ],
      },
    },
  },
  alerts: {
    allIds: [],
    byId: {},
  },
};
