// This state comes from adding `lambert_2.csv` and `violent_crimes.csv` files in the Crime and Heat analysis workflow
export const state = {
  ui: {
    hoveredColumnIds: [],
    selectedColumnIds: [],
    focusedColumnIds: [],
    visibleColumnIds: [],
    hiddenColumnIds: [],
    draggingColumnIds: [],
    dropTargetColumnIds: [],
    focusedObjectId: "o1",
    loadingOperations: [],
    selectedMatches: [],
  },
  operations: {
    allIds: ["o1"],
    byId: {
      o1: {
        id: "o1",
        name: null,
        databaseName: "o__ia4tu2_mkk4go28",
        operationType: "pack",
        parentId: null,
        childIds: ["t1", "t2"],
        columnIds: [],
        hiddenColumnIds: [],
        rowCount: null,
        isMaterialized: false,
        isInSync: false,
        joinType: "FULL OUTER",
        joinPredicate: "o1",
        joinKey1: null,
        joinKey2: null,
        matchStats: {
          matches: 0,
          left_unmatched: 0,
          right_unmatched: 0,
        },
        columnCount: null,
      },
    },
    rootOperationId: "o1",
  },
  tables: {
    allIds: ["t1", "t2"],
    byId: {
      t1: {
        id: "t1",
        parentId: "o1",
        source: "file upload",
        databaseName: "t_g8q8ny_mkk4glhf",
        name: "lambert_2",
        fileName: "lambert_2.csv",
        extension: "csv",
        size: 16225,
        mimeType: "text/csv",
        dateLastModified: 1730741525092,
        columnIds: [
          "c1",
          "c2",
          "c3",
          "c4",
          "c5",
          "c6",
          "c7",
          "c8",
          "c9",
          "c10",
          "c11",
          "c12",
          "c13",
          "c14",
          "c15",
          "c16",
          "c17",
          "c18",
          "c19",
          "c20",
          "c21",
        ],
        rowCount: 120,
        hiddenColumnIds: [],
      },
      t2: {
        id: "t2",
        parentId: "o1",
        source: "file upload",
        databaseName: "t_wxd8mx_mkk4glk4",
        name: "violent_crimes",
        fileName: "violent_crimes.csv",
        extension: "csv",
        size: 4508437,
        mimeType: "text/csv",
        dateLastModified: 1730741525096,
        columnIds: ["c22", "c23", "c24", "c25"],
        rowCount: 64739,
        hiddenColumnIds: [],
      },
    },
  },
  columns: {
    allIds: [
      "c1",
      "c2",
      "c3",
      "c4",
      "c5",
      "c6",
      "c7",
      "c8",
      "c9",
      "c10",
      "c11",
      "c12",
      "c13",
      "c14",
      "c15",
      "c16",
      "c17",
      "c18",
      "c19",
      "c20",
      "c21",
      "c22",
      "c23",
      "c24",
      "c25",
    ],
    byId: {
      c1: {
        id: "c1",
        parentId: "t1",
        name: null,
        databaseName: "STATION",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: "USW00013994",
        min: "USW00013994",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "USW00013994",
            count: 120,
          },
        ],
      },
      c2: {
        id: "c2",
        parentId: "t1",
        name: null,
        databaseName: "NAME",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
        min: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US",
            count: 120,
          },
        ],
      },
      c3: {
        id: "c3",
        parentId: "t1",
        name: null,
        databaseName: "DATE",
        columnType: "VARCHAR",
        approxUnique: 123,
        avg: null,
        count: 120,
        max: "2018-04-30",
        min: "2018-01-01",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "2018-01-03",
            count: 1,
          },
          {
            value: "2018-01-05",
            count: 1,
          },
          {
            value: "2018-01-06",
            count: 1,
          },
          {
            value: "2018-01-07",
            count: 1,
          },
          {
            value: "2018-01-09",
            count: 1,
          },
          {
            value: "2018-01-10",
            count: 1,
          },
          {
            value: "2018-01-11",
            count: 1,
          },
          {
            value: "2018-01-12",
            count: 1,
          },
          {
            value: "2018-01-13",
            count: 1,
          },
          {
            value: "2018-01-14",
            count: 1,
          },
          {
            value: "2018-01-15",
            count: 1,
          },
          {
            value: "2018-01-17",
            count: 1,
          },
          {
            value: "2018-01-18",
            count: 1,
          },
          {
            value: "2018-01-19",
            count: 1,
          },
          {
            value: "2018-01-20",
            count: 1,
          },
          {
            value: "2018-01-16",
            count: 1,
          },
          {
            value: "2018-01-08",
            count: 1,
          },
          {
            value: "2018-01-04",
            count: 1,
          },
          {
            value: "2018-01-02",
            count: 1,
          },
          {
            value: "2018-01-01",
            count: 1,
          },
        ],
      },
      c4: {
        id: "c4",
        parentId: "t1",
        name: null,
        databaseName: "PRCP",
        columnType: "DOUBLE",
        approxUnique: 28,
        avg: 0.1323333333333333,
        count: 120,
        max: 1.73,
        min: 0,
        nullPercentage: 0,
        std: 0.31127747985966975,
        topValues: [
          {
            value: "0.0",
            count: 80,
          },
          {
            value: "0.01",
            count: 5,
          },
          {
            value: "0.26",
            count: 3,
          },
          {
            value: "0.02",
            count: 2,
          },
          {
            value: "0.04",
            count: 2,
          },
          {
            value: "0.28",
            count: 2,
          },
          {
            value: "0.27",
            count: 2,
          },
          {
            value: "0.03",
            count: 1,
          },
          {
            value: "1.04",
            count: 1,
          },
          {
            value: "0.76",
            count: 1,
          },
          {
            value: "0.29",
            count: 1,
          },
          {
            value: "0.31",
            count: 1,
          },
          {
            value: "1.73",
            count: 1,
          },
          {
            value: "0.89",
            count: 1,
          },
          {
            value: "1.43",
            count: 1,
          },
          {
            value: "0.1",
            count: 1,
          },
          {
            value: "0.34",
            count: 1,
          },
          {
            value: "0.62",
            count: 1,
          },
          {
            value: "0.2",
            count: 1,
          },
          {
            value: "0.13",
            count: 1,
          },
        ],
      },
      c5: {
        id: "c5",
        parentId: "t1",
        name: null,
        databaseName: "PRCP_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 2,
        avg: null,
        count: 120,
        max: "T,,W,2400",
        min: ",,W,2400",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: ",,W,2400",
            count: 84,
          },
          {
            value: "T,,W,2400",
            count: 36,
          },
        ],
      },
      c6: {
        id: "c6",
        parentId: "t1",
        name: null,
        databaseName: "TMAX",
        columnType: "DOUBLE",
        approxUnique: 59,
        avg: 49.8,
        count: 120,
        max: 85,
        min: 9,
        nullPercentage: 0,
        std: 15.543703634883022,
        topValues: [
          {
            value: "48.0",
            count: 7,
          },
          {
            value: "57.0",
            count: 6,
          },
          {
            value: "50.0",
            count: 5,
          },
          {
            value: "69.0",
            count: 5,
          },
          {
            value: "43.0",
            count: 5,
          },
          {
            value: "53.0",
            count: 4,
          },
          {
            value: "56.0",
            count: 4,
          },
          {
            value: "60.0",
            count: 4,
          },
          {
            value: "62.0",
            count: 4,
          },
          {
            value: "38.0",
            count: 4,
          },
          {
            value: "42.0",
            count: 4,
          },
          {
            value: "34.0",
            count: 3,
          },
          {
            value: "72.0",
            count: 3,
          },
          {
            value: "59.0",
            count: 3,
          },
          {
            value: "66.0",
            count: 3,
          },
          {
            value: "52.0",
            count: 3,
          },
          {
            value: "51.0",
            count: 3,
          },
          {
            value: "45.0",
            count: 3,
          },
          {
            value: "39.0",
            count: 2,
          },
          {
            value: "29.0",
            count: 2,
          },
        ],
      },
      c7: {
        id: "c7",
        parentId: "t1",
        name: null,
        databaseName: "TMAX_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 120,
          },
        ],
      },
      c8: {
        id: "c8",
        parentId: "t1",
        name: null,
        databaseName: "TMIN",
        columnType: "DOUBLE",
        approxUnique: 46,
        avg: 30.408333333333335,
        count: 120,
        max: 61,
        min: -6,
        nullPercentage: 0,
        std: 12.963747664213482,
        topValues: [
          {
            value: "30.0",
            count: 7,
          },
          {
            value: "34.0",
            count: 7,
          },
          {
            value: "40.0",
            count: 6,
          },
          {
            value: "28.0",
            count: 6,
          },
          {
            value: "31.0",
            count: 5,
          },
          {
            value: "39.0",
            count: 5,
          },
          {
            value: "27.0",
            count: 5,
          },
          {
            value: "32.0",
            count: 5,
          },
          {
            value: "36.0",
            count: 4,
          },
          {
            value: "19.0",
            count: 4,
          },
          {
            value: "33.0",
            count: 4,
          },
          {
            value: "25.0",
            count: 3,
          },
          {
            value: "35.0",
            count: 3,
          },
          {
            value: "16.0",
            count: 3,
          },
          {
            value: "44.0",
            count: 3,
          },
          {
            value: "51.0",
            count: 3,
          },
          {
            value: "50.0",
            count: 3,
          },
          {
            value: "42.0",
            count: 3,
          },
          {
            value: "38.0",
            count: 3,
          },
          {
            value: "8.0",
            count: 2,
          },
        ],
      },
      c9: {
        id: "c9",
        parentId: "t1",
        name: null,
        databaseName: "TMIN_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 120,
          },
        ],
      },
      c10: {
        id: "c10",
        parentId: "t1",
        name: null,
        databaseName: "WT01",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.7,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 36,
          },
        ],
      },
      c11: {
        id: "c11",
        parentId: "t1",
        name: null,
        databaseName: "WT01_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.7,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 36,
          },
        ],
      },
      c12: {
        id: "c12",
        parentId: "t1",
        name: null,
        databaseName: "WT02",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.975,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 3,
          },
        ],
      },
      c13: {
        id: "c13",
        parentId: "t1",
        name: null,
        databaseName: "WT02_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.975,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 3,
          },
        ],
      },
      c14: {
        id: "c14",
        parentId: "t1",
        name: null,
        databaseName: "WT03",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.9,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 12,
          },
        ],
      },
      c15: {
        id: "c15",
        parentId: "t1",
        name: null,
        databaseName: "WT03_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.9,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 12,
          },
        ],
      },
      c16: {
        id: "c16",
        parentId: "t1",
        name: null,
        databaseName: "WT04",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.9833,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 2,
          },
        ],
      },
      c17: {
        id: "c17",
        parentId: "t1",
        name: null,
        databaseName: "WT04_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.9833,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 2,
          },
        ],
      },
      c18: {
        id: "c18",
        parentId: "t1",
        name: null,
        databaseName: "WT06",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.9917,
        std: null,
        topValues: [
          {
            value: "1.0",
            count: 1,
          },
        ],
      },
      c19: {
        id: "c19",
        parentId: "t1",
        name: null,
        databaseName: "WT06_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.9917,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 1,
          },
        ],
      },
      c20: {
        id: "c20",
        parentId: "t1",
        name: null,
        databaseName: "WT08",
        columnType: "DOUBLE",
        approxUnique: 1,
        avg: 1,
        count: 120,
        max: 1,
        min: 1,
        nullPercentage: 0.9583,
        std: 0,
        topValues: [
          {
            value: "1.0",
            count: 5,
          },
        ],
      },
      c21: {
        id: "c21",
        parentId: "t1",
        name: null,
        databaseName: "WT08_ATTRIBUTES",
        columnType: "VARCHAR",
        approxUnique: 1,
        avg: null,
        count: 120,
        max: ",,W",
        min: ",,W",
        nullPercentage: 0.9583,
        std: null,
        topValues: [
          {
            value: ",,W",
            count: 5,
          },
        ],
      },
      c22: {
        id: "c22",
        parentId: "t2",
        name: null,
        databaseName: "Date",
        columnType: "VARCHAR",
        approxUnique: 53765,
        avg: null,
        count: 64739,
        max: "2018-04-30T22:26:00",
        min: "1900-01-01T00:00:00",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "2014-12-07T20:30:00",
            count: 40,
          },
          {
            value: "2015-06-20T23:33:00",
            count: 29,
          },
          {
            value: "2012-02-10T16:11:00",
            count: 24,
          },
          {
            value: "2014-08-12T15:00:00",
            count: 20,
          },
          {
            value: "2012-01-01T00:01:00",
            count: 19,
          },
          {
            value: "2017-09-15T22:30:00",
            count: 17,
          },
          {
            value: "2012-04-15T19:47:00",
            count: 17,
          },
          {
            value: "2010-04-08T15:25:00",
            count: 17,
          },
          {
            value: "2010-01-01T00:01:00",
            count: 16,
          },
          {
            value: "2010-01-22T18:53:00",
            count: 15,
          },
          {
            value: "2017-09-15T09:00:00",
            count: 15,
          },
          {
            value: "2012-03-17T20:32:00",
            count: 15,
          },
          {
            value: "2008-11-29T21:07:00",
            count: 14,
          },
          {
            value: "2009-02-05T20:05:00",
            count: 14,
          },
          {
            value: "2009-03-20T21:40:00",
            count: 14,
          },
          {
            value: "2014-01-01T00:01:00",
            count: 13,
          },
          {
            value: "2010-08-28T21:10:00",
            count: 12,
          },
          {
            value: "2011-05-07T01:14:00",
            count: 12,
          },
          {
            value: "2014-11-24T22:00:00",
            count: 11,
          },
          {
            value: "2018-01-24T18:00:00",
            count: 11,
          },
        ],
      },
      c23: {
        id: "c23",
        parentId: "t2",
        name: null,
        databaseName: "Count",
        columnType: "DOUBLE",
        approxUnique: 2,
        avg: 0.9653068474953274,
        count: 64739,
        max: 1,
        min: -1,
        nullPercentage: 0,
        std: 0.2611201703973508,
        topValues: [
          {
            value: "1.0",
            count: 63616,
          },
          {
            value: "-1.0",
            count: 1123,
          },
        ],
      },
      c24: {
        id: "c24",
        parentId: "t2",
        name: null,
        databaseName: "Crime",
        columnType: "DOUBLE",
        approxUnique: 160,
        avg: 36789.82055638796,
        count: 64739,
        max: 44205,
        min: 10000,
        nullPercentage: 0,
        std: 7437.627729958122,
        topValues: [
          {
            value: "41011.0",
            count: 12573,
          },
          {
            value: "31111.0",
            count: 9612,
          },
          {
            value: "31421.0",
            count: 4551,
          },
          {
            value: "41013.0",
            count: 3810,
          },
          {
            value: "43012.0",
            count: 2589,
          },
          {
            value: "21000.0",
            count: 2581,
          },
          {
            value: "43013.0",
            count: 2368,
          },
          {
            value: "41021.0",
            count: 2185,
          },
          {
            value: "10000.0",
            count: 1778,
          },
          {
            value: "42011.0",
            count: 1309,
          },
          {
            value: "43015.0",
            count: 1277,
          },
          {
            value: "43016.0",
            count: 1247,
          },
          {
            value: "31112.0",
            count: 1125,
          },
          {
            value: "41016.0",
            count: 1001,
          },
          {
            value: "42013.0",
            count: 857,
          },
          {
            value: "32111.0",
            count: 810,
          },
          {
            value: "42014.0",
            count: 796,
          },
          {
            value: "36111.0",
            count: 786,
          },
          {
            value: "44015.0",
            count: 750,
          },
          {
            value: "44013.0",
            count: 662,
          },
        ],
      },
      c25: {
        id: "c25",
        parentId: "t2",
        name: null,
        databaseName: "Description",
        columnType: "VARCHAR",
        approxUnique: 210,
        avg: null,
        count: 64739,
        max: "ROBBERY-RESIDENCE/STRNGARM/NO INJ/SUCCESS",
        min: "AGG.ASSAULT-FIREARM/CITIZEN ADULT 1ST DEGREE",
        nullPercentage: 0,
        std: null,
        topValues: [
          {
            value: "AGG.ASSAULT-FIREARM/CITIZEN ADULT 1ST DEGREE",
            count: 12394,
          },
          {
            value: "ROBBERY-HIGHWAY  /FIREARM USED/SUCCESSFUL",
            count: 9533,
          },
          {
            value: "ROBBERY-HIGHWAY  /STRNGARM/NO INJ/SUCCESS",
            count: 4524,
          },
          {
            value: "AGG.ASSAULT-FIREARM/CITIZEN ADULT 3RD DEGREE",
            count: 3774,
          },
          {
            value: "AGG.ASSAULT-OTH DANG WEP/CTZEN ADLT 2ND DEGREE",
            count: 2573,
          },
          {
            value: "RAPE -- FORCIBLE",
            count: 2559,
          },
          {
            value: "AGG.ASSAULT-OTH DANG WEP/CTZEN ADLT 3RD DEGREE",
            count: 2332,
          },
          {
            value: "AGG.ASSAULT-FIREARM/CITIZEN CHILD 1ST DEGREE",
            count: 2164,
          },
          {
            value: "HOMICIDE",
            count: 1762,
          },
          {
            value: "AGG.ASSAULT-KNIFE/CITIZEN ADULT 1ST DEGREE",
            count: 1301,
          },
          {
            value: "ASSLT-AGGRAV-OTH-WPN-2ND-ADULT-DOMESTIC",
            count: 1274,
          },
          {
            value: "ASSLT-AGGRAV-OTH-WPN-3RD-ADULT-DOMESTIC",
            count: 1230,
          },
          {
            value: "ROBBERY-HIGHWAY     /FIREARM USED/ATTEMPT",
            count: 1117,
          },
          {
            value: "ASSLT-AGGRAV-FIREARM-3RD-ADULT-DOMESTIC",
            count: 982,
          },
          {
            value: "AGG.ASSAULT-KNIFE/CITIZEN ADULT 3RD DEGREE",
            count: 851,
          },
          {
            value: "ROBBERY-RESIDENCE/FIREARM USED/SUCCESSFUL",
            count: 805,
          },
          {
            value: "ASSLT-AGGRV-KNIFE/CUT-1ST-ADULT-DOMESTIC",
            count: 791,
          },
          {
            value: "ROBBERY-COMMERCE PL/FIREARM USED/SUCCESS",
            count: 773,
          },
          {
            value: "ASSLT-AGGRV-HND/FST/FT-2ND-ADUL-DOMESTIC",
            count: 743,
          },
          {
            value: "AGG.ASSAULT-HNDS,FST,FEET/CTZEN ADLT 3RD DEGRE",
            count: 651,
          },
        ],
      },
    },
  },
  alerts: {
    allIds: ["o1_JOIN_KEY_LEFT_MISSING", "o1_JOIN_KEY_RIGHT_MISSING"],
    byId: {
      o1_JOIN_KEY_LEFT_MISSING: {
        timeStamp: 1768764076501,
        code: "JOIN_KEY_LEFT_MISSING",
        name: "Missing join key",
        description:
          "Pack operations require that the user specify a join key in the left-hand table.",
        severity: "error",
        sourceId: "o1",
        isPassing: false,
        isSilenced: false,
        message:
          'Pack operation "null" is missing a join key in the left table.',
        id: "o1_JOIN_KEY_LEFT_MISSING",
      },
      o1_JOIN_KEY_RIGHT_MISSING: {
        timeStamp: 1768764076501,
        code: "JOIN_KEY_RIGHT_MISSING",
        name: "Missing join key",
        description:
          "Pack operations require that the user specify a join key in the right-hand table.",
        severity: "error",
        sourceId: "o1",
        isPassing: false,
        isSilenced: false,
        message:
          'Pack operation "null" is missing a join key in the right table.',
        id: "o1_JOIN_KEY_RIGHT_MISSING",
      },
    },
  },
};
