title: "Roundup"
description: "A click-based data integration system for data journalists"
baseurl: "/docs"
url: "../"

theme: just-the-docs
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md

nav_external_links:
  - title: "Demo"
    url: "../demo"
    opens_in_new_tab: false
  - title: "GitHub Repository"
    url: "https://github.com/steve-kasica/roundup"
    opens_in_new_tab: false
  # - title: "Issue Tracker"
  #   url: "https://github.com/steve-kasica/roundup/issues"
  #   opens_in_new_tab: false
  # - title: "Discussion"
  #   url: "https://github.com/steve-kasica/roundup/discussions"
  #   opens_in_new_tab: false
